name: Hosting Static Website

on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        run: |
          echo "Starting the build job"
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup nodejs'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install
      - run: npm run build
      - run: npm i react-router bootstrap reactstrap uuid

      - name: 'Write config'
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
          echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
          echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
          echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/oci_api_key.pem
          echo "${{secrets.OCI_KEY_PUBLIC}}" >> ~/.oci/oci_api_key_public.pem
      - name: 'Install OCI CLI'
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          exec -l $SHELL
      - name: 'Fix Config File Permissions'
        run: |
          oci setup repair-file-permissions --file /home/runner/.oci/config
          oci setup repair-file-permissions --file /home/runner/.oci/oci_api_key.pem
      - name: 'Deploy Into Object Storage'
        run: |
          fn create context z4nmuh --provider oracle
          fn use context z4nmuh
          fn update context oracle.compartment-id ocid1.tenancy.oc1..aaaaaaaacijxtvpzccpzikjzwfb3zw6mpscemhz2kdfienj7vwuc4ltliq2q
          fn update context api-url https://functions.ap-sydney-1.oraclecloud.com
          fn update context registry syd.ocir.io/sdzrwidjruyr/fauzanmuh
          docker login -u 'sdzrwidjruyr/oracleidentitycloudservice/1941720171@student.polinema.ac.id' syd.ocir.io -p ${{secrets.AUTH_TOKEN}}
          fn --verbose deploy --app node-app
          fn invoke node-app react-crud

      - name: 'Login to Dockerhub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and push'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/coba-kuis .
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/coba-kuis